package io.github.martinsjavacode.parkingmanagement.domain.model.revenue

import io.github.martinsjavacode.parkingmanagement.domain.enums.CurrencyType
import java.math.BigDecimal
import java.time.LocalDate

/**
 * Represents the revenue generated by a parking lot on a specific date.
 *
 * This class stores information about the accumulated revenue
 * for a given parking lot on a specific date.
 *
 * @property id Unique identifier of the revenue record, nullable for new instances
 * @property parkingId Identifier of the parking lot associated with this revenue
 * @property date Date the revenue pertains to
 * @property amount Total revenue amount
 * @property currency Currency type of the revenue (e.g., BRL, USD)
 */
data class Revenue(
    val id: Long? = null,
    val parkingId: Long,
    val date: LocalDate,
    val amount: BigDecimal,
    val currency: CurrencyType,
)
