-- Table: Parking
CREATE TABLE IF NOT EXISTS parking
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sector_name            VARCHAR(50) UNIQUE NOT NULL,
    base_price             NUMERIC(10, 2)     NOT NULL,
    max_capacity           INT                NOT NULL,
    open_hour              TIME               NOT NULL,
    close_hour             TIME               NOT NULL,
    duration_limit_minutes INT                NOT NULL,
    CONSTRAINT PK_PARKING PRIMARY KEY (id)
);

CREATE INDEX IX_PARKING_SECTOR_NAME ON parking (sector_name);

-- Table: ParkingSpot
CREATE TABLE IF NOT EXISTS parking_spots
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parking_id BIGINT        NOT NULL REFERENCES parking (id),
    latitude   NUMERIC(9, 6) NOT NULL,
    longitude  NUMERIC(9, 6) NOT NULL,
    CONSTRAINT PK_PARKING_SPOT PRIMARY KEY (id)
);

CREATE INDEX IDX_PARKING_SPOT_PARKING_ID ON parking_spots (parking_id);

-- Table: ParkingEvent
CREATE TABLE IF NOT EXISTS parking_events
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    license_plate VARCHAR(20) NOT NULL,
    latitude      NUMERIC(9, 6),
    longitude     NUMERIC(9, 6),
    entry_time    TIMESTAMP   NOT NULL,
    exit_time     TIMESTAMP,
    event_type    VARCHAR(10) NOT NULL,
    CONSTRAINT PK_PARKING_EVENT PRIMARY KEY (id),
    CONSTRAINT CK_PARKING_EVENT_TYPE CHECK (event_type IN ('ENTRY', 'PARKED', 'EXIT'))
);

CREATE INDEX IDX_PARKING_EVENT_LICENSE_PLATE ON parking_events (license_plate);
CREATE INDEX IDX_PARKING_EVENT_PARKING_SPOTS_ID ON parking_spots (id);
CREATE INDEX IDX_PARKING_EVENT_EVENT_TYPE ON parking_events (event_type);

-- Table: Revenue
CREATE TABLE IF NOT EXISTS revenues
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parking_id BIGINT         NOT NULL REFERENCES parking (id),
    date       DATE           NOT NULL,
    amount     NUMERIC(10, 2) NOT NULL,
    currency   VARCHAR(10)    NOT NULL,
    CONSTRAINT PK_REVENUE PRIMARY KEY (id)
);

CREATE INDEX IDX_REVENUE_ON_PARKING_DATE ON revenues (parking_id, date);

