-- Table: Parking
CREATE TABLE IF NOT EXISTS parking
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sector_name            VARCHAR(50)    NOT NULL,
    base_price             NUMERIC(10, 2) NOT NULL,
    max_capacity           INT            NOT NULL,
    open_hour              TIME           NOT NULL,
    close_hour             TIME           NOT NULL,
    duration_limit_minutes INT            NOT NULL,
    CONSTRAINT PK_PARKING PRIMARY KEY (id)
);

CREATE INDEX IX_PARKING_SECTOR_NAME ON parking (sector_name);

-- Table: ParkingSpot
CREATE TABLE IF NOT EXISTS parking_spots
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parking_id BIGINT        NOT NULL REFERENCES parking (id),
    latitude   NUMERIC(9, 6) NOT NULL,
    longitude  NUMERIC(9, 6) NOT NULL,
    CONSTRAINT PK_PARKING_SPOT PRIMARY KEY (id)
);

CREATE INDEX IDX_PARKING_SPOT_PARKING_ID ON parking_spots (parking_id);

-- Table: Vehicle
CREATE TABLE IF NOT EXISTS vehicles
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    license_plate VARCHAR(20) NOT NULL,
    CONSTRAINT PK_VEHICLE PRIMARY KEY (id),
    CONSTRAINT UC_VEHICLE_LICENSE_PLATE UNIQUE (license_plate)
);

CREATE INDEX IDX_VEHICLE_LICENSE_PLATE ON vehicles (license_plate);

-- Table: EntryEvent
CREATE TABLE IF NOT EXISTS entry_events
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    license_plate VARCHAR(20) NOT NULL REFERENCES vehicles (license_plate),
    parking_id    BIGINT      NOT NULL REFERENCES parking (id),
    entry_time    TIMESTAMP   NOT NULL,
    event_type    VARCHAR(10) NOT NULL,
    CONSTRAINT PK_ENTRY_EVENT PRIMARY KEY (id),
    CONSTRAINT CK_ENTRY_EVENT_TYPE CHECK (event_type IN ('ENTRY', 'EXIT'))
);

CREATE INDEX IDX_ENTRY_EVENT_LICENSE_PLATE ON entry_events (license_plate);
CREATE INDEX IDX_ENTRY_EVENT_PARKING_ID ON entry_events (parking_id);
CREATE INDEX IDX_ENTRY_EVENT_EVENT_TYPE ON entry_events (event_type);

-- Table: SpotEvent
CREATE TABLE IF NOT EXISTS spot_events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parking_spot_id BIGINT      NOT NULL REFERENCES parking_spots (id),
    license_plate   VARCHAR(20) NOT NULL REFERENCES vehicles (license_plate),
    event_type      VARCHAR(10) NOT NULL,
    event_time      TIMESTAMP   NOT NULL,
    CONSTRAINT PK_SPOT_EVENT PRIMARY KEY (id),
    CONSTRAINT CK_SPOT_EVENT_TYPE CHECK (event_type IN ('PARKED', 'UNPARKED'))
);

CREATE INDEX IDX_SPOT_EVENT_PARKING_SPOT_ID ON spot_events (parking_spot_id);
CREATE INDEX IDX_SPOT_EVENT_LICENSE_PLATE ON spot_events (license_plate);
CREATE INDEX IDX_SPOT_EVENT_EVENT_TYPE ON spot_events (event_type);

-- Table: Revenue
CREATE TABLE IF NOT EXISTS revenues
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    parking_id BIGINT         NOT NULL REFERENCES parking (id),
    date       DATE           NOT NULL,
    amount     NUMERIC(10, 2) NOT NULL,
    currency   VARCHAR(10)    NOT NULL,
    CONSTRAINT PK_REVENUE PRIMARY KEY (id)
);

CREATE INDEX IDX_REVENUE_PARKING_ID ON revenues (parking_id);
CREATE INDEX IDX_REVENUE_DATE ON revenues (date);

